name: PvPCore
version: ${project.version}
main: net.corddevs.pvpcore.Main
authors: [ Nemijah, SlowNewt, Cinr, ym3n ]
commands:
  kills:
  deaths:
  kits:
    aliases: [kit]
  resetcooldowns:
  clear:
    aliases: [cl]
  tp:
    aliases: [teleport]
  tphere:
  dm:
  dr:
  gamemode:
    aliases: [gm]

  freeze:
    aliases: [f]
  unfreeze:
    aliases: [uf]
  fly:
  staff:
    aliases: [staffmode, sm, s, StaffMode]
