name: PvPCore
version: ${project.version}
main: net.corddevs.pvpcore.Main
authors: [ Nemijah, SlowNewt, ym3n, benjables ]
depend:
  - LuckPerms
  - PlaceholderAPI
  - ActionBarAPI
commands:
  fly:
    description: Enables / Disables your flight
  tp:
    aliases: [teleport]
    description: teleports you to a player
  tphere:
    aliases: [teleporthere]
    description: teleports a player to you
  freeze:
    description: Freezes a player
  clear:
    description: clears your inventory
    aliases: [cl, ci, cls, cli]
  gamemode:
    description: change your gamemode
    aliases: [gm]
  staff:
    description: toggle staff mode
    aliases: [staffmode, sm, StaffMode]
  vanish:
    description: vanish from normal players
    aliases: [v]