name: PvPCore
version: ${project.version}
main: net.corddevs.pvpcore.Main
authors: [ Nemijah, SlowNewt, ym3n, benjables ]
depend:
  - LuckPerms
  - PlaceholderAPI
  - ActionBarAPI
commands:
  kills:
  deaths:
  kits:
    aliases: [kit]
  resetcooldowns:
  clear:
    aliases: [cl]
  tp:
    aliases: [teleport]
  tphere:
  dm:
  dr:
  gamemode:
    aliases: [gm]
  fly:
  staff:
    aliases: [staffmode, sm, s, StaffMode]
  vanish:
    aliases: [v]
  freeze:
    aliases: []
  setspawn:
  spawn:
