name: PvPCore
version: 1.0
main: net.corddevs.pvpcore.Main
authors: [ Nemijah, SlowNewt ]
commands:
  kills:
  deaths:
  kits:
    aliases: [kit]
  resetcooldowns:
  clear:
    aliases: [cl]
  tp:
    aliases: [teleport]
  dm:
  dr: